### ISSUE TITLE
'process killed' problem in cutting planes approach (without fixing 'k')

### ISSUE THREAD

**Issue by arinik9** [ls-cwi/yoshiko#16]
Hello,

First, I would like to thank you for your contribution for this project
I started to use your code to solve Cluster Editing problem (without fixing `k`) with cutting planes approach. First, I used the standalone version. Then, I had to get your current code source in github and compile it  in a server. I am able to run and to get results for small complete signed graphes (up to 80 nodes). However, when I use a complete signed graph with 100 nodes, I get the following error 2-3 hours later after have run the program: "process killed". I think it might be memory problem. But, I'm not sure yet about it. That is why I create an issue.

I also changed the memory parameter in cplex, I tried 2 different parameters, one is low memory(1gb) and the other high memory(50gb) (I run the program in a server where the ram is about 500gb):
```
cplex.setParam(IloCplex::WorkMem, 1024);
cplex.setParam(IloCplex::NodeFileInd,2);
```
and

```
cplex.setParam(IloCplex::WorkMem, 50000);
cplex.setParam(IloCplex::NodeFileInd,2);
```

But I stil get the same problem: "process killed"
This is how I run the program:
`./yoshiko.2.2.0 -F 0 -st -sp -f network100.jena -v 4 -o result`

I send you the network with which I got the problem.
[network100.jena.zip](https://github.com/ls-cwi/yoshiko/files/1828494/network100.jena.zip)

I look forward to hearing from you. Thanks in advance

**Comment by spqrPh** [comment]
Hi,

a couple of questions while I'm trying to reproduce this:
From which branch (or even better commit) exactly did you compile the executable, also I assume you are running this on some sort of high performance cluster (at least that is what 500 GB RAM sounds like) so I'm wondering what sort of rights you have on this cluster? Are there limitations in terms of memory or runtime that might be interfering with your run?

**Comment by arinik9** [comment]
Hi,
I cloned directly the project, so the branch `master`. The last commit is `4745875 Possible Fix for Merge Heuristic`. Regarding the rights, I am a regular user in a server that is shared by multiple regular users, so I do not have any root permission. Honestly, I do not know if there are specific limitations in terms of memory or runtime that might be interfering with your run, but what I can say is that I have already run Cplex-based programs in the same server without problem/crash.

Actually, I need an optimal solution for the given network, that is why there is not any interest of using heuristics. 

The reason I would like to use the -st and -tp parameters is that cutting planes approach take much less time compared to pure Cplex-based approach (i.e. without usercuttback/lazycallback).
For instance, It takes 2 days with the given network based on  pure Cplex-based approach. However, my goal is to reduce this amount of time by using  cutting planes approach (around 2-3 hours maybe).

An additional thing: I used the [standalone version](http://www.mi.fu-berlin.de/w/LiSA/YoshikoCharles) as well before haved used this github project. The same problem (i.e. the crash) exists. I assume that the source of the crash is not because of the my user rights in the server (or specific limitations in terms of memory, etc.)

Is it easily possible to get a log file? I mean, maybe you generate some sort of log files in your development process.

Thank you for your quick response.

**Comment by spqrPh** [comment]
hey,

so I ran your instance in both heuristic (super quick, EC ~390) and ILP mode without the callbacks and got the optimal solution (EC ~360 I believe) in about one day of calculation on a HPC without any errors. I will try again using both callbacks, it might be related to the implementation of those specific callbacks. "Process killed" sounds like some limitation by the system though. While I haven't gotten any crashes with those callbacks yet it might be that they just consume too much memory. Could you get any information from your administrators? There should be some sort of log keeping track of processes that were killed while exceeding limits

Sadly the software doesn't write a log yet (that should def. be added in the future though), however you could run it with the verbosity switch set to highest (-v 5) and pipe the output into some file (on unix systems usually with someCommand > someFile.txt  ). If you could do that and track down where the program crashes for you it could be helpful, I will get back to you when I have additional results

**Comment by spqrPh** [comment]
So I just ran the instance with your parameters (both switches turned on) and got the optimal solution (EC:361) in 6096.3 seconds (so with a significant speed-up!). There were no crashes.  So it looks like there might actually be a limitation on your HPC causing the problem

Keep in mind that CPLEX might be writing branches to files when you manually limit its memory usage and then you might run into disk space quotas. Looking forward to hear from you about your experience and I hope you will find a solution

**Comment by arinik9** [comment]
Hi, thank you for your promp reply.

Good news in your side!
Could you please tell me the characteristics of your computer (RAM, disk space, etc.)?
Also, could you please tell me what the meaning of  `EC` is?
Also, for `HPC` ? high performance computing ?

In my side, that is right, this is a problem coming from my system, and this is indeed a problem of `out of memory`. But, in spite of limiting explicitly memory usage in Cplex (first, 1Gb and then 50 Gb) I ran into this problem. Maybe am I doing wrong? Or you specify the memory usage somewhere else, therefore my memory declaration is not taken into account?
I send you the related part of the log output from the command `dmseg`. Do you think it is a problem of RAM memory or disk space memory?

I would like to emphasize that I have the same problem with my 2 personal computers. And it is always the `out of memory` problem. So, I would like to get your opinion about the possible solution if you have some time.
I look forward to hearing from you.

**Comment by guwek** [comment]
Hi Nejat,

There is no way to prevent this behaviour if you want optimal solutions. Cplex will branch at a certain point.  The branch-and-bound tree can get huge. It is then a question of how much memory you have available whether you will run out of memory or not. It seems that we have more memory available. Check with your cluster administration.

I think EC refers to editing costs. 

Best regards,
Gunnar

**Comment by spqrPh** [comment]
Seems like you're running CPLEX via Java? I believe Java has some virtual management for memory, you might need to allocate it via -xms / -xmx (just google the parameters for the java distribution and version you are using)

Alternatively you could take a look at the CPLEX parameter NodeFileInd, this allows you to write the branches to files (increases runtime by a lot) instead of using RAM/ virtual memory.

**Comment by arinik9** [comment]
Thanks for your prompt replies.

I see what you men @guwek , I thought it could be somehow possible to limit the memory usage (for instance, with the Cplex `NodeFileInd` parameter), that is why I created this issue, though.

To conclude this discussion, @spqrPh you said that the program took 6096.3 seconds with cutting planes approach. Could you please tell me what the characteristics of your machine are? Thus, I'll have an idea about memory requirement, then I'll contact the cluster administration.

By the way, I've already used the `NodeFileInd` parameter with `WorkMem` (cf. discussion above). Maybe I need to try  `NodeFileInd` alone. Thanks fro your suggestions, though!

**Comment by spqrPh** [comment]
I believe I had a limit of about 512 GB but didn't even get close to that, it also worked with the callbacks on my local machine (8GB RAM) without issues, are you calling CPLEX via Java and if so what heap size do you provide for the JVM?

**Comment by arinik9** [comment]
@spqrPh thanks again for your kindness for answering my questions. I forgot to close this issue. So, I'm closing it
